services:
  opensearch-node:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node
    environment:
      - discovery.type=single-node
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_PASSWORD}"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "${OPENSEARCH_PORT-9200}:9200"

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
      - "OPENSEARCH_HOSTS=${OPENSEARCH_HOST}:${OPENSEARCH_PORT}"

  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    ports:
      - "${OLLAMA_PORT-11434}:11434"

  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - "${OPEN_WEBUI_PORT-3000}:8080"
    environment:
      - 'OLLAMA_BASE_URL=${OLLAMA_BASE_URL}:${OLLAMA_PORT}'
      - 'WEBUI_SECRET_KEY='
      - 'VECTOR_DB=opensearch'
      - 'OPENSEARCH_URI=${OPENSEARCH_HOST}:${OPENSEARCH_PORT}'
      - 'OPENSEARCH_USERNAME=${OPENSEARCH_USERNAME}'
      - 'OPENSEARCH_PASSWORD=${OPENSEARCH_PASSWORD}'
      - 'OPENSEARCH_SSL=false'
      - 'OPENSEARCH_CERT_VERIFY=false'
      - 'ENABLE_RAG_WEB_LOADER_SSL_VERIFICATION=false'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  ollama: {}
  open-webui: {}